version: '3'
services:

  test-db:
    container_name: test-db
    image: test-db
    build: ./db/
    ports:
      - "3306:3306"
    volumes:
      - ./db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d

  test-liquibase:
    container_name: test-liquibase
    image: liquibase/liquibase
    command: --url='jdbc:mysql://test-db:3306/test_db' --changeLogFile=changelog.xml --username=root --password=password update
    volumes:
      - ./config/changelog.xml:/liquibase/changelog.xml
      - ./lib:/liquibase/lib
      - ./scripts:/liquibase/scripts
    links:
      - test-db
volumes:
  test-db-volume: {}
